/**
 * This file was auto-generated by scripts/generate-operation-map.mjs
 * Do not make direct changes to the file.
 */

/** Runtime mapping: Operation name → { path, method } */
export const OPERATION_MAP = {
  AppController_getHealth: { path: '/health', method: 'get' },
  AuthorsController_create: { path: '/authors', method: 'post' },
  AuthorsController_findAll: { path: '/authors', method: 'get' },
  AuthorsController_findOne: { path: '/authors/{id}', method: 'get' },
  AuthorsController_remove: { path: '/authors/{id}', method: 'delete' },
  AuthorsController_update: { path: '/authors/{id}', method: 'patch' },
  PostsController_create: { path: '/posts', method: 'post' },
  PostsController_findAll: { path: '/posts', method: 'get' },
  PostsController_findOne: { path: '/posts/{id}', method: 'get' },
  PostsController_remove: { path: '/posts/{id}', method: 'delete' },
  PostsController_update: { path: '/posts/{id}', method: 'patch' },
} as const;

export type OperationMap = typeof OPERATION_MAP;
